-- 코드를 입력하세요
# Union 방법
# (SELECT ANIMAL_ID, NAME, 'O' as 중성화
# FROM ANIMAL_INS
# WHERE SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%') 
# UNION
# (SELECT ANIMAL_ID, NAME, 'X' as 중성화
# FROM ANIMAL_INS
# WHERE SEX_UPON_INTAKE NOT LIKE '%Neutered%' AND SEX_UPON_INTAKE NOT LIKE '%Spayed%')
# ORDER BY ANIMAL_ID;

# Case 문!
SELECT ANIMAL_ID, NAME,
    CASE
        WHEN SEX_UPON_INTAKE LIKE '%Neutered%' THEN 'O'
        WHEN SEX_UPON_INTAKE LIKE '%Spayed%' THEN 'O'
        ELSE 'X'
    END as 중성화
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;